services:
  - type: web
    name: fastapi-backend
    env: python
    plan: starter
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-key
      - key: OTHER_SECRET
        value: something-else