name: Weekly Pinecone Upload

on:
  schedule:
    - cron: '0 12 * * 2'  # every Tuesday at 12:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Recreate service_account_key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_JSON_B64 }}" | base64 --decode > service_account_key.json

      - name: Run scraper
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          python app/scraper.py
        env:
          LIGHTHOUSE_FILE_ID: ${{ secrets.LIGHTHOUSE_FILE_ID }}
          LIGHTHOUSE_PAGES: ${{ secrets.LIGHTHOUSE_PAGES }}

      - name: Run text processor
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          python app/text_processor.py
        env:
          LIGHTHOUSE_FILE_ID: ${{ secrets.LIGHTHOUSE_FILE_ID }}
          EMBEDDED_CHUNKS_FILE_ID: ${{ secrets.EMBEDDED_CHUNKS_FILE_ID }}
          LIGHTHOUSE_PAGES: ${{ secrets.LIGHTHOUSE_PAGES }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PINECONE_KEY: ${{ secrets.PINECONE_KEY }}
          PINECONE_ENV: ${{ secrets.PINECONE_ENV }}
          PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
          EMBEDDED_METADATA_FILE: ${{ secrets.EMBEDDED_METADATA_FILE }}

